ALTER TABLE public.courses
ADD COLUMN IF NOT EXISTS has_lab BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS num_sessions_per_week INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS lecture_duration INTEGER DEFAULT 90,
ADD COLUMN IF NOT EXISTS lab_duration INTEGER DEFAULT 150; 

