import "./globals.css";

export const metadata = {
  title: "Capstone Prototype",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="background-primary">
      <body>{children}</body>
    </html>
  );
}
