"use client";
import { useState, useRef, useEffect } from "react";
import dummydata from "./dummydata.json";

export default function ScheduleManager() {
  // setSubmittedSchedulesData persistent state logic generated by AI using Perplexity
  const [submittedSchedulesData, setSubmittedSchedulesData] = useState(() => {
    if (typeof window !== "undefined") {
      const storedData = localStorage.getItem("submittedSchedulesData");
      return storedData ? JSON.parse(storedData) : dummydata;
    }
    return dummydata;
  });
  const [sortOption, setSortOption] = useState("");
  const [searchParams, setSearchParams] = useState("");
  const [timeslotUploadDetails, setTimeslotUploadDetails] = useState({
    fileName: "",
    uploadTime: "",
  });
  const [errorMessage, setErrorMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [successMessage, setSuccessMessage] = useState("");
  const [uploadedTimeslot, setUploadedTimeslot] = useState(null);
  const fileInputRef = useRef(null); //reference for file input element
  const [scheduleToUpload, setScheduleToUpload] = useState(null); //track which schedule is getting their timeslot uploaded

  // This code block was AI generated using Perplexity
  // Persist submittedSchedulesData to localStorage whenever it changes
  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("submittedSchedulesData", JSON.stringify(submittedSchedulesData));
    }
  }, [submittedSchedulesData]);

  // Sorting the schedules
  const sortData = (data, option) => {
    if (!option) return data;
    else {
      switch (option) {
        case "newest":
        //   return [...data].sort((a, b) => new Date(b.dateSubmitted) - new Date(a.dateSubmitted));
        // case "oldest":
        //   return [...data].sort((a, b) => new Date(a.dateSubmitted) - new Date(b.dateSubmitted));
        case "title-a":
          return [...data].sort((a, b) => a.title.localeCompare(b.title));
        case "title-z":
          return [...data].sort((a, b) => b.title.localeCompare(a.title));
        case "program":
          return [...data].sort((a, b) => a.programType.localeCompare(b.programType));
        case "status":
          return [...data].sort((a, b) => a.status.localeCompare(b.status));
        case "timeslots":
          return [...data].sort((a, b) => a.timeslots.localeCompare(b.timeslots));
        default:
          return submittedSchedulesData;
      }
    }
  }

  // Searching
  const search = (data, params) => {
    if (!params) return submittedSchedulesData;
    else {
      const lowercasedParams = params.toLowerCase();
      return data.filter(item =>
        item.title.toLowerCase().includes(lowercasedParams) ||
        item.programType.toLowerCase().includes(lowercasedParams) ||
        item.status.toLowerCase().includes(lowercasedParams) ||
        item.timeslots.toLowerCase().includes(lowercasedParams)
        // item.dateSubmitted.toLowerCase().includes(lowercasedParams)
      );
    }   
  }

  // Handle sort
  const handleSortChange = (e) => {
    setSortOption(e.target.value);
  }

  // Handle search
  const handleSearchChange = (e) => {
    setSearchParams(e.target.value);
  }

  // Get chip colour based on program type, status, timeslots

  // Program type colour conditional rendering
  const getProgramTypeColour = (programType) => {
    switch (programType.toLowerCase()) {
      case "diploma":
        return "chip-diploma pl-2 pr-5 py-1.5 rounded border border-1";
      case "certificate":
        return "chip-certificate px-2 py-1.5 rounded border border-1";
      case "bachelors":
        return "chip-bachelors pl-2 pr-3 py-1.5 rounded border border-1";
    }
  };

  // Status colour conditional rendering
  const getStatusColour = (status) => {
    switch (status.toLowerCase()) {
      case "approved":
        return "chip-approved pl-2 pr-3 py-1.5 rounded border border-1 text-justify-center";
      case "submitted":
        return "chip-submitted px-2 py-1.5 rounded border border-1 text-justify-center";
      case "in review":
        return "chip-inreview pl-2 pr-4 py-1.5 rounded border border-1 text-justify-center";
      case "rejected":
        return "chip-rejected pl-2 pr-6 py-1.5 rounded border border-1 text-justify-center";
    }
  };

  // Timeslot colour conditional rendering
  const getTimeslotsColour = (timeslots) => {
    if (timeslots.toLowerCase().includes("uploaded")) {
      return "chip-uploaded px-2.5 py-1.5 rounded border border-1 cursor-pointer hover:optacity-80";
    } else {
      return "chip-empty pl-2 pr-4 py-1.5 rounded border border-1 cursor-pointer hover:opacity-80";
    }
  };

  // Display sorted/searched data
  let displayedData = submittedSchedulesData;
  if (searchParams) {
    displayedData = search(submittedSchedulesData, searchParams);
  }
  if (sortOption) {
    displayedData = sortData(displayedData, sortOption);
  }

  // Allow for file upload input & open user's device file explorer
  const handleTimeslotUploadClick = (index) => {
    if (!isLoading && fileInputRef.current) {
      setScheduleToUpload(index);
      fileInputRef.current.click();
    }
  }

  // Adapted from @app/Frontend/ScheduleManager/UploadData/page.js
  // Validate file type for timeslot upload
  const validateFile = (file) => {
    const validTypes = [
      "application/vnd.ms-excel",
      "text/csv",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/pdf"
    ];
    return validTypes.includes(file.type) || file.name.match(/\.(xlsx|csv|pdf)$/i);
  };

  // Adapted from @app/Frontend/ScheduleManager/UploadData/page.js
  // Actually do the timeslot upload
  const handleTimeslotUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    try {
      setIsLoading(true);
      setSuccessMessage("");
      setErrorMessage("");

      if (!validateFile(file)) {
        throw new Error("Invalid file type. Please upload an Excel, CSV, or PDF file.");
      }

      setUploadedTimeslot(file);
      setTimeslotUploadDetails({
        fileName: file.name,
        uploadTime: new Date().toLocaleDateString(),
      });

      setSuccessMessage("Timeslot successfully uploaded.");

      // -------------UNCOMMENT THIS BLOCK WHEN BACKEND IS READY!-------------
      // Backend logic of upload functionality
      // const formData = new FormData();
      // formData.append("timeslotFile", file);

      // try {
      //   const response = await fetch("http://localhost:5000/admin/upload", {
      //     method: "POST",
      //     body: formData,
      //   });

      //   const result = await response.json();
      //   if (!response.ok) throw new Error("File upload failed");
      //   setUploadedTimeslot(result);
      //   setTimeslotUploadDetails({
      //     fileName: result.fileName,
      //     uploadTime: result.uploadTime,
      //   });
      // } catch (error) {
      //   setErrorMessage(error.message);
      //   setTimeslotUploadDetails({
      //     fileName: "",
      //     uploadTime: "",
      //   });
      //   setUploadedTimeslot(null);
      // }
      // Finish up process in front-end
      // ----------------------------------------------------------------------

    } catch (error) {
      setErrorMessage(error.message);
      setTimeslotUploadDetails({
        fileName: "",
        uploadTime: "",
      });
      setUploadedTimeslot(null);
    } finally {
      setIsLoading(false);
    }

    const schedulesUpdated = submittedSchedulesData.map((schedule, index) => {
    if (index === scheduleToUpload) {
      return {
        ...schedule,
        timeslots: `Uploaded ${new Date().toLocaleDateString()}`,
        fileName: timeslotUploadDetails.fileName
      };
    }
    return schedule;
  });
  setSubmittedSchedulesData(schedulesUpdated);
  };

  return (
    /*Main Content Container*/
    <div className="p-8">
      {/* Filter/Sort & Search */}
      <div className="flex flex-row items-center justify-center gap-10 pb-8">
        {/* Filter/Sort Container */}
        <div className="text-lg text-bold flex items-center gap-1">Sort by
          <select className="px-3 py-2 mx-3 background-primary rounded-lg border border-tertiary focus:outline-offset-1 focus:outline-2 focus:border-tertiary w-xs text-gray-500" onChange={handleSortChange} value={sortOption}>
            <option disabled selected className="text-gray-400">Select an option</option>
            <option value="newest" className="text-primary">Date Submitted, newest</option>
            <option value="oldest" className="text-primary">Date Submitted, oldest</option>
            <option value="title-a" className="text-primary">Title, A-Z</option>
            <option value="title-z" className="text-primary">Title, Z-A</option>
            <option value="program" className="text-primary">Program Type</option>
            <option value="status" className="text-primary">Status</option>
            <option value="timeslots" className="text-primary">Timeslots uploaded</option>
          </select>
        </div>
        {/* Search */}
        <div className="text-lg text-bold flex items-center gap-1">Search
          <input
            type="text"
            placeholder="Enter search criteria (e.g. keyword, status, tags...)"
            className="px-3 py-2 ml-3 background-primary rounded-lg border border-tertiary focus:outline-offset-1 focus:outline-2 focus:border-tertiary w-3xl" value={searchParams} onChange={handleSearchChange}
          />
          </div>
      </div>
      {/* Hidden file input - This code block was AI generated using Perplexity */}
      <input
        ref={fileInputRef}
        type="file"
        className="hidden"
        accept=".xlsx, .csv, .pdf"
        onChange={handleTimeslotUpload}
        disabled={isLoading}
      />
      {/* Error Message */}
      {errorMessage && (
        <div className="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-lg mb-6">
          <p>{errorMessage}</p>
        </div>
      )}
      {/* Success Message */}
      {successMessage && (
        <div className="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 rounded-lg mb-6">
          <p>{successMessage}</p>
        </div>
      )}
      {/* Table Container */}
        <div className="bg-gray-100 m-0 rounded-lg shadow-md">
          <div className="h-[calc(100vh-269px)] overflow-y-auto overflow-x-hidden">
            <table className="table-auto min-w-full">
              <thead className="bg-gray-300 sticky top-0">
                <tr className="grid grid-cols-6 gap-8 py-3 text-left font-sm pl-6">
                  <th>Date Submitted</th>
                  <th>Title</th>
                  <th>Program Type</th>
                  <th>Status</th>
                  <th>Timeslots</th>
                </tr>
              </thead>
              <tbody>
                {displayedData.map((schedule, index) => (
                  <tr key={index} className="grid grid-cols-6 gap-8 py-3 border-b pl-6">
                    <td className="mt-1 self-center">{schedule.dateSubmitted}</td>
                    <td className="mt-1 self-center">{schedule.title}</td>
                    <td className="p-4-md mt-1.5 text-justify-center self-center">
                      <span className={getProgramTypeColour(schedule.programType)}>{schedule.programType}</span>
                    </td>
                    <td className="mt-1.5 self-center">
                      <span className={getStatusColour(schedule.status)}>{schedule.status}</span>
                    </td>
                    <td className="mt-1 self-center">
                      <button className={`${getTimeslotsColour(schedule.timeslots)}`} onClick={() => handleTimeslotUploadClick(index)}>
                        {schedule.timeslots.toLowerCase().includes("uploaded") ? 
                        (<div>
                          <span className="font-semibold self-center">{schedule.timeslots}</span>
                          <span className="ml-2 italic opacity-70 text-xs underline"> (Click to upload new)</span>
                        </div>)
                        : " Empty - Upload Now"}
                      </button>
                    </td>
                    <td className="flex justify-left mx-12 self-center">
                      <button className="button-primary text-white px-4 py-1.5 rounded hover:button-hover active:button-clicked">View</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
    </div>
    );
}